In [16]:
import pandas as pd
from glob import glob
import numpy as np
from scipy import sparse

In [2]:
import sys, os
sys.path.insert(0, os.path.abspath('../'))

In [5]:
from src.features.smali import SmaliHIN

In [17]:
glob('/Volumes/Lexar/processed/*')

['/Volumes/Lexar/processed/P.npz',
 '/Volumes/Lexar/processed/B.npz',
 '/Volumes/Lexar/processed/meta.csv',
 '/Volumes/Lexar/processed/A.npy']

In [21]:
P_fp, B_fp, meta_fp, A_fp = glob('/Volumes/Lexar/processed/*')

In [22]:
%time A_mat = np.load(A_fp)

CPU times: user 1.95 ms, sys: 9.01 s, total: 9.01 s
Wall time: 29.9 s


In [23]:
A_mat = sparse.csr_matrix(A_mat)

In [24]:
A_mat

<662x1409841 sparse matrix of type '<class 'numpy.longlong'>'
	with 8539727 stored elements in Compressed Sparse Row format>

In [8]:
B_mat = sparse.load_npz(B_fp)
P_mat = sparse.load_npz(P_fp)

In [9]:
%time mtp0 = A_mat.dot(B_mat).dot(A_mat.T)

CPU times: user 115 ms, sys: 17.4 ms, total: 133 ms
Wall time: 132 ms


In [10]:
mtp0.todense()

matrix([[ 379632,  301067,  479981,  669551,  903743,    5247,  456796,
          578733,  632767,  792286],
        [ 301067,  406640,  462838,  683327,  980311,    6950,  410097,
          576105,  651733,  863117],
        [ 479981,  462838,  739842,  899197, 1224792,    8247,  588380,
          777808,  883019, 1108724],
        [ 669551,  683327,  899197, 1686389, 1923602,   12266,  890226,
         1240172, 1312728, 1746709],
        [ 903743,  980311, 1224792, 1923602, 3295457,   17159, 1167250,
         1590223, 1658548, 2179150],
        [   5247,    6950,    8247,   12266,   17159,    5133,    7273,
            9874,   11376,   16384],
        [ 456796,  410097,  588380,  890226, 1167250,    7273,  628773,
          783502,  797569, 1036259],
        [ 578733,  576105,  777808, 1240172, 1590223,    9874,  783502,
         1176002, 1121682, 1437120],
        [ 632767,  651733,  883019, 1312728, 1658548,   11376,  797569,
         1121682, 1562840, 1524456],
        [ 792286,  

In [11]:
%time mtp1 = A_mat.dot(P_mat).dot(A_mat.T)

CPU times: user 49.9 ms, sys: 5.3 ms, total: 55.2 ms
Wall time: 53.7 ms


In [12]:
mtp1.todense()

matrix([[ 479610,  113101,  504926,  606065,  684912,    1314,  562478,
          654242,  564254,  610314],
        [ 113101,  189670,  154808,  282921,  291490,    1248,  213495,
          258657,  213665,  294432],
        [ 504926,  154808,  642758,  690068,  776894,    1644,  603748,
          718772,  646286,  724223],
        [ 606065,  282921,  690068, 2231337, 1945225,    1927,  971079,
         1451271, 1247155, 1948868],
        [ 684912,  291490,  776894, 1945225, 3745027,    2154, 1085531,
         1602493, 1196638, 1955694],
        [   1314,    1248,    1644,    1927,    2154,    2179,    1499,
            1907,    1925,    2148],
        [ 562478,  213495,  603748,  971079, 1085531,    1499,  931271,
         1037347,  761556,  977619],
        [ 654242,  258657,  718772, 1451271, 1602493,    1907, 1037347,
         1577420, 1089420, 1466432],
        [ 564254,  213665,  646286, 1247155, 1196638,    1925,  761556,
         1089420, 1414376, 1290901],
        [ 610314,  

In [13]:
# APBP^TA^T
%time mtp2 = A_mat*P_mat*B_mat*P_mat.T*A_mat.T

CPU times: user 357 ms, sys: 21.4 ms, total: 378 ms
Wall time: 378 ms


In [14]:
mtp2.todense()

matrix([[24223400184,  9603665842, 26437080965, 42104382080, 42628202096,
            40179462, 31395021697, 38655246769, 36635108459, 42432305601],
        [ 9603665842,  7239907377, 11701966113, 20645797624, 21654210592,
            36391148, 14366848138, 18520867721, 17158349367, 21241672460],
        [26437080965, 11701966113, 29750567624, 47335430164, 48386534097,
            53695902, 34637789813, 43184263335, 41407092103, 47988445257],
        [42104382080, 20645797624, 47335430164, 86811207564, 87962268629,
            78149555, 58908984023, 75857402495, 69523322360, 87478430750],
        [42628202096, 21654210592, 48386534097, 87962268629, 91780432333,
            86471744, 59721686487, 77015091295, 70743703167, 89015244486],
        [   40179462,    36391148,    53695902,    78149555,    86471744,
              859077,    54829314,    72285776,    72684048,    84095506],
        [31395021697, 14366848138, 34637789813, 58908984023, 59721686487,
            54829314, 4366068302